import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "packages/*/dist/**",
    // Claude Code worktrees contain transpiled package output that must
    // never be linted — they add thousands of bogus errors otherwise.
    "**/.claude/**",
    // CommonJS trees with their OWN eslint configs. The root Next flat config
    // has no CommonJS override, so it (wrongly) flags their `require()` calls as
    // no-require-imports. The desktop app ships dopl-desktop-app/eslint.config.js
    // (authoritative — run `cd dopl-desktop-app && npx eslint main/`); the
    // scripts/ tree is Node CLI tooling. Neither belongs to the Next app lint.
    "dopl-desktop-app/**",
    "scripts/**",
  ]),

  // FIX L1 — ENGINEERING.md §2's 500-line hard cap, ENFORCED on the web app and
  // the workspace packages. It was written down and never wired up here (only
  // `dopl-desktop-app/eslint.config.js` had the rule), so `src/**` grew past it
  // silently — `shared/auth/mcp-oauth.ts` crossed to EXACTLY 500 during the
  // production-hardening round with nothing to say so. Same severity and same
  // options as the desktop config, on purpose: one cap, one meaning.
  {
    files: ["src/**/*.{ts,tsx}", "packages/*/src/**/*.{ts,tsx}"],
    rules: {
      "max-lines": ["error", { max: 500, skipBlankLines: false, skipComments: false }],
    },
  },

  // The BACKLOG, listed rather than hidden. Every one of these was already over
  // the cap when the rule landed; turning the rule on with a blanket ignore, or
  // refactoring fourteen unrelated files inside a hardening round, were both
  // worse than naming them. New code is capped; these stay visible and shrink
  // one at a time. DO NOT ADD TO THIS LIST — split the file instead. Tracked as
  // a finding in docs/REFACTOR-FINDINGS.md.
  {
    files: [
      "src/shared/supabase/types.ts", // 2290 — GENERATED by the Supabase CLI
      "src/features/channels/lib/group-thread.test.ts",
      "packages/mcp-server/src/server.ts",
      "src/features/skills/components/skill-view.tsx",
      "packages/dopl-client/src/client.ts",
      "src/features/knowledge/server/seed-fixtures-data.ts",
      "src/shared/layout/settings-modal/sections/plans-billing.tsx",
      "src/features/channels/lib/group-thread.ts",
      "src/features/billing/server/webhook-handler.test.ts",
      "src/features/ontology/server/repository.ts",
      "src/features/workspaces/server/invitations.ts",
      "src/features/channels/components/channels-view.tsx",
      "src/features/teams/server/repository.ts",
      "src/features/billing/components/upgrade-modal.tsx",
      // NOT exempted, deliberately: `src/shared/auth/mcp-oauth.ts` sits at
      // EXACTLY 500 and therefore passes. It is the file whose silent growth
      // prompted this rule, and leaving it enforced means the next line added
      // to it fails the lint — which is the whole point.
    ],
    rules: { "max-lines": "off" },
  },
]);

export default eslintConfig;
