import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "packages/*/dist/**",
    // Claude Code worktrees contain transpiled package output that must
    // never be linted — they add thousands of bogus errors otherwise.
    "**/.claude/**",
    // CommonJS trees with their OWN eslint configs. The root Next flat config
    // has no CommonJS override, so it (wrongly) flags their `require()` calls as
    // no-require-imports. The desktop app ships dopl-desktop-app/eslint.config.js
    // (authoritative — run `cd dopl-desktop-app && npx eslint main/`); the
    // scripts/ tree is Node CLI tooling. Neither belongs to the Next app lint.
    "dopl-desktop-app/**",
    "scripts/**",
  ]),

  // FIX L1 — ENGINEERING.md §2's 500-line hard cap, ENFORCED on the web app and
  // the workspace packages. It was written down and never wired up here (only
  // `dopl-desktop-app/eslint.config.js` had the rule), so `src/**` grew past it
  // silently — `shared/auth/mcp-oauth.ts` crossed to EXACTLY 500 during the
  // production-hardening round with nothing to say so. Same severity and same
  // options as the desktop config, on purpose: one cap, one meaning.
  {
    files: [
      "src/**/*.{ts,tsx}",
      "packages/*/src/**/*.{ts,tsx}",
      "apps/*/src/**/*.{ts,tsx}",
    ],
    rules: {
      "max-lines": ["error", { max: 500, skipBlankLines: false, skipComments: false }],
    },
  },

  // The SPA's fence around web-tree reuse: `@/` maps to the repo-root web
  // tree (so reused feature modules' own imports resolve verbatim), which
  // makes it POSSIBLE to import things that must never enter the renderer
  // bundle. Next-coupled modules already fail the vite build (unresolvable
  // `next/*`), but the app router tree and the server layers would bundle
  // silently — fence them here. See apps/desktop-ui/CONVENTIONS.md.
  {
    files: ["apps/*/src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            { group: ["@/app/*"], message: "Next app-router tree — never bundled into the SPA. Reuse lives under @/features/* and @/shared/*." },
            { group: ["@/features/*/server/*", "@/shared/supabase/admin", "@/shared/auth/*"], message: "Server-only module — the renderer talks to the API, never to services or Supabase." },
            { group: ["next", "next/*"], message: "No Next in the SPA." },
          ],
        },
      ],
    },
  },

  // The BACKLOG, listed rather than hidden. Every one of these was already over
  // the cap when the rule landed; turning the rule on with a blanket ignore, or
  // refactoring fourteen unrelated files inside a hardening round, were both
  // worse than naming them. New code is capped; these stay visible and shrink
  // one at a time. DO NOT ADD TO THIS LIST — split the file instead. Tracked as
  // a finding in docs/REFACTOR-FINDINGS.md.
  {
    files: [
      "src/shared/supabase/types.ts", // ~2934 (drifts with every gen) — GENERATED by the Supabase CLI
      // REMOVED, not moved (2026-08-08): `packages/mcp-server/src/server.ts` was
      // 1045 — the largest hand-written file in the tree and §2's "most overdue
      // split" — and is now 227. It became the thin registrar the 2026-07-20
      // op-dispatch precedent asks for (boot the session, build the gates, wire
      // the ten domain registrars), against six new siblings all under the cap:
      // `instructions.ts` 173, `workspace-directory.ts` 174, `gating.ts` 216,
      // `registrar.ts` 313, `status-footer.ts` 97, `meta-tools.ts` 150. The four
      // gates kept their topology exactly — two at registration, two per call,
      // hoisted OUT of the wrapper because `registerMetaTool` bypasses it — and
      // the three gating tables moved with them, so `parity-harness.ts` now
      // parses `gating.ts` (the parse follows the constant, not the filename).
      // REMOVED, not renamed (2026-08-07): `skills/components/skill-view.tsx`
      // was 832 and is now 381 — the editor save-chain, the 412-conflict record
      // and the metadata CAS clock became three hooks, and its two local
      // sub-components became sibling files. Under the cap, so the exemption is
      // gone rather than moved.
      // REMOVED, not renamed (2026-08-08): `packages/dopl-client/src/client.ts`
      // was 720 — the table's longest-running row — and is now 34. This is the
      // per-domain method-group split §2 had been scheduling since the
      // `ChannelAgentsClient` link was deleted: `DoplClient` is still ONE flat
      // class, but its methods are declared across a chain of
      // `client-<domain>.ts` links (see `client-base.ts` for the order), and
      // the cluster/workflow/workspace HTTP that was still inline moved into
      // `clusters.ts` / `workflows.ts` / `workspaces.ts` beside the domain
      // modules that already existed. (Two of those three, and their chain
      // links, were deleted with workflows + clusters on 2026-08-11.)
      //
      // WHAT THE SPLIT DID AND DID NOT CHANGE, corrected (2026-08-08). This
      // used to claim "Public API byte-frozen — `index.d.ts` is unchanged",
      // which is not true of the file: `dist/index.d.ts` differs by 6 lines
      // against HEAD. None of that is the split's doing — the changed lines are
      // three type re-export rows (a dropped `KnowledgeTrashSnapshot` and
      // `TrashedChat`, and the ontology summary types the `getOntology`
      // overload added). The accurate claim is the narrower one: the FLATTENED
      // CLASS SURFACE is unchanged BY THE SPLIT. The 85 methods
      // `src/client-surface.test.ts` pinned were the POST-TEARDOWN surface (67
      // since the 2026-08-11 deletion; that file states the arithmetic), not
      // the pre-split one — HEAD declared 92, and the seven trash-teardown
      // methods (`listChatsTrash`, `listKbTrash`, `restoreChat`,
      // `restoreKbBase`, `restoreKbEntry`, `restoreKbFolder`,
      // `restoreOntologyCluster`) left the class in a SEPARATE change that
      // happened to land in the same working tree. Two edits, one diff; the
      // split moved methods between files and removed none.
      "src/features/knowledge/server/seed-fixtures-data.ts",
      // REMOVED, not renamed: `settings-modal/sections/plans-billing.tsx` was
      // split for the desktop port into a 103-line web binding, the Stripe-free
      // `plans-billing-core.tsx`, and `plan-cards.tsx`. All three are under the
      // cap, so the exemption is gone rather than moved.
      // REMOVED, not moved (2026-08-08, F-176/F-041): `channels/lib/group-thread.ts`
      // was 819 — "the fastest-growing file in the tree" — and is now 428, split
      // by reason-to-change into `group-thread-types.ts` (the render model),
      // `group-thread-markers.ts` (the reserved metadata markers, read strictly),
      // `group-thread-render.ts` (the card's read side) and `group-thread-draft.ts`
      // (the accumulator + its derivations). The grouping state machine stays
      // whole per §2's reducer carve-out, and every public name is re-exported
      // from `group-thread.ts`, so no importer changed. Its 983-line test file
      // split along the same seams and is likewise gone from this list.
      "src/features/billing/server/webhook-handler.test.ts",
      // REMOVED (2026-08-07): `ontology/server/repository.ts` was 538 and is now
      // 488 — the soft-delete/restore/purge read paths went with the trash
      // teardown, and the cascade delete moved into an RPC.
      // REMOVED, not moved (2026-08-10, C-20): `workspaces/server/invitations.ts`
      // was 534 and is now 404 — member ADMINISTRATION (`updateMemberRole`,
      // `removeMember`, `countActiveOwners`) split into
      // `membership-admin.ts` (209), which is where the channels departure
      // sweep is wired. The original keeps the two-name re-export every caller
      // already imports, so no importer moved. A real split, not a trimmed
      // comment.
      // REMOVED (2026-08-07): `channels/components/channels-view-core.tsx` was
      // 588 and is now 439. Roughly a third of that was DELETION, not
      // extraction — the four hand-rolled optimistic override records (notify
      // scope, tool profile, trust, consent) and their lens memos stopped
      // existing once those writes patch the query cache every reader already
      // reads. The shared mutation layer subsumed the pattern instead of
      // becoming a fifth copy of it.
      // REMOVED (2026-08-08): `teams/server/repository.ts` was 625 and is now
      // 114 — split by table group into `repository-members.ts` (149),
      // `repository-grants.ts` (229) and `repository-resources.ts` (189), with
      // the original kept as the `teams` rows plus the re-export surface every
      // caller already imports. Removed, not moved.
      "src/features/billing/components/upgrade-modal.tsx",
      // NOT exempted, deliberately: `src/shared/auth/mcp-oauth.ts` sits at 498
      // and therefore passes. (It read "EXACTLY 500" here, which was true when
      // written and is the kind of number that rots — re-measure before
      // repeating it.) It is the file whose silent growth prompted this rule,
      // and leaving it enforced means it has two lines of headroom and no
      // more — which is the whole point.
    ],
    rules: { "max-lines": "off" },
  },
]);

export default eslintConfig;
