"use client";

/**
 * ConnectionPanelBody — singleton panel that auto-generates an API key and
 * shows platform-specific setup instructions. Tabs: Claude Code, OpenClaw, Other.
 */

import { useEffect, useState, useCallback, useRef } from "react";
import { Copy, Check } from "lucide-react";
import { MonoLabel } from "@/components/design";
import type { ConnectionPanelData } from "../types";

interface ApiKey {
  id: string;
  key_prefix: string;
  name: string;
  created_at: string;
  last_used_at: string | null;
  revoked_at: string | null;
}

interface ConnectionPanelBodyProps {
  panel: ConnectionPanelData;
}

type Platform = "claude" | "openclaw" | "other";

export function ConnectionPanelBody({ panel }: ConnectionPanelBodyProps) {
  const [apiKey, setApiKey] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [platform, setPlatform] = useState<Platform>("claude");
  const autoGenerated = useRef(false);

  const ensureKey = useCallback(async () => {
    try {
      const res = await fetch("/api/user/keys");
      if (res.ok) {
        const data = await res.json();
        const active = (data.keys || []).filter((k: ApiKey) => !k.revoked_at);
        if (active.length > 0) {
          if (!autoGenerated.current) {
            autoGenerated.current = true;
            const genRes = await fetch("/api/user/keys", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ name: "MCP Connection" }),
            });
            if (genRes.ok) {
              const genData = await genRes.json();
              setApiKey(genData.key);
            }
          }
          setLoading(false);
          return;
        }
      }

      if (!autoGenerated.current) {
        autoGenerated.current = true;
        const genRes = await fetch("/api/user/keys", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ name: "MCP Connection" }),
        });
        if (genRes.ok) {
          const genData = await genRes.json();
          setApiKey(genData.key);
        }
      }
    } catch {
      // Silently fail
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    ensureKey();
  }, [ensureKey]);

  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  function copy(text: string, section?: string) {
    if (typeof navigator === "undefined") return;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setCopiedSection(section ?? null);
    setTimeout(() => { setCopied(false); setCopiedSection(null); }, 2000);
  }

  function maskKey(key: string) {
    if (key.length <= 8) return key;
    return key.slice(0, 8) + "****************";
  }

  // ── Platform-specific configs ──────────────────────────────────
  // No DOPL_BASE_URL needed: the MCP server defaults to https://www.usedopl.com

  const claudeCliCommand = apiKey
    ? `claude mcp add dopl --scope user --transport stdio -- npx @dopl/mcp-server --api-key ${apiKey}`
    : null;

  const claudeMcpConfig = apiKey
    ? JSON.stringify(
        {
          mcpServers: {
            dopl: {
              command: "npx",
              args: ["@dopl/mcp-server", "--api-key", apiKey],
            },
          },
        },
        null,
        2
      )
    : null;

  const openclawMcpConfig = apiKey
    ? JSON.stringify(
        {
          mcp: {
            servers: {
              dopl: {
                command: "npx",
                args: ["@dopl/mcp-server", "--api-key", apiKey],
              },
            },
          },
        },
        null,
        2
      )
    : null;

  const genericMcpConfig = apiKey
    ? JSON.stringify(
        {
          dopl: {
            command: "npx",
            args: ["@dopl/mcp-server", "--api-key", apiKey],
          },
        },
        null,
        2
      )
    : null;

  const agentsMd = apiKey
    ? `# Dopl — MCP Connection

You are being given credentials to connect to Dopl.
Connect to this MCP server, then explain to the user what you just connected to.

## Connect

Add this MCP server to your configuration. This is a standard MCP stdio server.

\`\`\`json
{
  "dopl": {
    "command": "npx",
    "args": ["@dopl/mcp-server", "--api-key", "${apiKey}"]
  }
}
\`\`\`

Where to put this depends on your platform:
- Claude Code CLI: run \`claude mcp add dopl --scope user --transport stdio -- npx @dopl/mcp-server --api-key ${apiKey}\`
- Claude Desktop (macOS): add to ~/Library/Application Support/Claude/claude_desktop_config.json under "mcpServers"
- Claude Desktop (Windows): add to %APPDATA%\\Claude\\claude_desktop_config.json under "mcpServers"
- OpenClaw: add to ~/.openclaw/config/mcporter.json under "mcp.servers"
- VS Code / Cursor / Windsurf: add to .mcp.json in project root under "mcpServers"
- Any other MCP-compatible tool: add to that tool's MCP server config

## After connecting

Once connected, explain to the user that they are now connected to **Dopl** — a curated knowledge base of real-world AI and automation setups. The server provides its own context about available capabilities and tools, so you'll automatically know what you can do.
`
    : null;

  // ── Render ──────────────────────────────────────────────────────

  function CopyBtn({ text, id }: { text: string; id: string }) {
    return (
      <button
        onClick={() => copy(text, id)}
        className="absolute top-2 right-2 z-10 text-white/30 hover:text-white/70 transition-colors"
        title="Copy"
      >
        {copiedSection === id ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
      </button>
    );
  }

  function CodeBlock({ text, id }: { text: string; id: string }) {
    return (
      <div className="relative">
        <CopyBtn text={text} id={id} />
        <pre className="text-[10px] font-mono bg-black/[0.3] border border-white/[0.08] rounded-[3px] p-3 pr-8 overflow-auto text-white/80 leading-relaxed whitespace-pre-wrap break-all">
          {text}
        </pre>
      </div>
    );
  }

  return (
    <div className="flex-1 min-h-0 overflow-y-auto p-4 space-y-4">
      {loading ? (
        <div className="flex items-center gap-2 py-8 justify-center">
          <div className="w-3 h-3 rounded-full bg-accent-primary/40 animate-pulse" />
          <p className="text-xs text-white/40 font-mono">Generating connection...</p>
        </div>
      ) : apiKey && agentsMd ? (
        <>
          {/* Platform tabs */}
          <div className="flex gap-1 p-0.5 rounded-[4px] bg-white/[0.04]">
            {(
              [
                { id: "claude" as Platform, label: "Claude Code" },
                { id: "openclaw" as Platform, label: "OpenClaw" },
                { id: "other" as Platform, label: "Other" },
              ] as const
            ).map((tab) => (
              <button
                key={tab.id}
                type="button"
                onClick={() => setPlatform(tab.id)}
                className={`flex-1 px-2 py-1.5 font-mono text-[10px] uppercase tracking-wider rounded-[3px] transition-colors ${
                  platform === tab.id
                    ? "bg-white/[0.1] text-white/90"
                    : "text-white/40 hover:text-white/60"
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* Claude Code tab */}
          {platform === "claude" && (
            <div className="space-y-3">
              <section className="space-y-1.5">
                <MonoLabel tone="muted">Run this command</MonoLabel>
                <CodeBlock text={claudeCliCommand!} id="cli" />
              </section>

              <div className="flex items-center gap-2">
                <div className="flex-1 h-px bg-white/[0.06]" />
                <span className="text-[9px] font-mono text-white/25 uppercase tracking-widest">or add to config</span>
                <div className="flex-1 h-px bg-white/[0.06]" />
              </div>

              <section className="space-y-1.5">
                <MonoLabel tone="muted">Claude Desktop / VS Code config</MonoLabel>
                <CodeBlock text={claudeMcpConfig!} id="claude-config" />
                <p className="text-[10px] text-white/30 leading-relaxed">
                  macOS: ~/Library/Application Support/Claude/claude_desktop_config.json
                  <br />
                  Windows: %APPDATA%\Claude\claude_desktop_config.json
                  <br />
                  VS Code / Cursor: .mcp.json in project root
                </p>
              </section>
            </div>
          )}

          {/* OpenClaw tab */}
          {platform === "openclaw" && (
            <div className="space-y-3">
              <section className="space-y-1.5">
                <MonoLabel tone="muted">Add to mcporter.json</MonoLabel>
                <CodeBlock text={openclawMcpConfig!} id="openclaw-config" />
                <p className="text-[10px] text-white/30 leading-relaxed">
                  Config file: ~/.openclaw/config/mcporter.json
                </p>
              </section>

              <section className="space-y-1.5">
                <MonoLabel tone="muted">Or add via CLI</MonoLabel>
                <CodeBlock
                  text={`openclaw mcp add dopl -- npx @dopl/mcp-server --api-key ${apiKey}`}
                  id="openclaw-cli"
                />
              </section>
            </div>
          )}

          {/* Other tab */}
          {platform === "other" && (
            <div className="space-y-3">
              <p className="text-xs text-white/70 leading-relaxed">
                Copy this and give it to any MCP-compatible AI tool. It will set up the connection.
              </p>

              <button
                onClick={() => copy(agentsMd)}
                className={`w-full px-4 py-2.5 rounded-[3px] font-mono text-[10px] uppercase tracking-wide
                  transition-all cursor-pointer ${
                    copied
                      ? "bg-emerald-500/[0.15] border border-emerald-500/[0.3] text-emerald-400"
                      : "bg-accent-primary/[0.12] hover:bg-accent-primary/[0.2] border border-accent-primary/[0.25] text-accent-primary"
                  }`}
              >
                {copied ? "Copied to clipboard" : "Copy all instructions"}
              </button>

              <section className="space-y-1.5">
                <MonoLabel tone="muted">Generic MCP Config</MonoLabel>
                <CodeBlock text={genericMcpConfig!} id="generic-config" />
              </section>

              <section className="space-y-1.5">
                <MonoLabel tone="muted">Full instructions</MonoLabel>
                <div className="relative">
                  <CopyBtn text={agentsMd} id="instructions" />
                  <pre className="text-[10px] font-mono bg-black/[0.3] border border-white/[0.08] rounded-[3px] p-3 pr-8 overflow-auto text-white/60 leading-relaxed max-h-[300px] whitespace-pre-wrap">
                    {agentsMd}
                  </pre>
                </div>
              </section>
            </div>
          )}

          {/* Shared: API Key + warning */}
          <div className="pt-1 border-t border-white/[0.06] space-y-3">
            <section className="space-y-1.5">
              <MonoLabel tone="muted">API Key</MonoLabel>
              <div className="relative px-3 py-2 rounded-[3px] bg-black/[0.3] border border-white/[0.08] text-xs font-mono text-white/90 break-all">
                <CopyBtn text={apiKey} id="key" />
                {maskKey(apiKey)}
              </div>
            </section>

            <div className="space-y-1">
              <p className="text-[10px] text-amber-400/60 leading-relaxed">
                Contains your API key. Do not share publicly.
              </p>
              <p className="text-[10px] text-white/30">
                Manage keys in{" "}
                <a href="/settings/keys" className="text-accent-primary/70 hover:text-accent-primary">
                  Settings
                </a>
              </p>
            </div>
          </div>
        </>
      ) : (
        <div className="py-8 text-center">
          <p className="text-xs text-white/40">
            Could not generate API key. Please try again or visit{" "}
            <a href="/settings/keys" className="text-accent-primary/70 hover:text-accent-primary">
              Settings
            </a>.
          </p>
        </div>
      )}
    </div>
  );
}
