"use client";

/**
 * ConnectionPanelBody — singleton panel that auto-generates an API key and
 * shows a ready-to-copy agents.md file. Tool-agnostic — works with any
 * MCP-compatible AI tool (Claude, OpenClaw, Cursor, Windsurf, etc.).
 */

import { useEffect, useState, useCallback, useRef } from "react";
import { Copy, Check } from "lucide-react";
import { MonoLabel } from "@/components/design";
import type { ConnectionPanelData } from "../types";

interface ApiKey {
  id: string;
  key_prefix: string;
  name: string;
  created_at: string;
  last_used_at: string | null;
  revoked_at: string | null;
}

interface ConnectionPanelBodyProps {
  panel: ConnectionPanelData;
}

export function ConnectionPanelBody({ panel }: ConnectionPanelBodyProps) {
  const [baseUrl, setBaseUrl] = useState<string>("");
  const [apiKey, setApiKey] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const autoGenerated = useRef(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setBaseUrl(window.location.origin);
    }
  }, []);

  const ensureKey = useCallback(async () => {
    try {
      const res = await fetch("/api/user/keys");
      if (res.ok) {
        const data = await res.json();
        const active = (data.keys || []).filter((k: ApiKey) => !k.revoked_at);
        if (active.length > 0) {
          if (!autoGenerated.current) {
            autoGenerated.current = true;
            const genRes = await fetch("/api/user/keys", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ name: "MCP Connection" }),
            });
            if (genRes.ok) {
              const genData = await genRes.json();
              setApiKey(genData.key);
            }
          }
          setLoading(false);
          return;
        }
      }

      if (!autoGenerated.current) {
        autoGenerated.current = true;
        const genRes = await fetch("/api/user/keys", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ name: "MCP Connection" }),
        });
        if (genRes.ok) {
          const genData = await genRes.json();
          setApiKey(genData.key);
        }
      }
    } catch {
      // Silently fail
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    ensureKey();
  }, [ensureKey]);

  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  function copy(text: string, section?: string) {
    if (typeof navigator === "undefined") return;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setCopiedSection(section ?? null);
    setTimeout(() => { setCopied(false); setCopiedSection(null); }, 2000);
  }

  function maskKey(key: string) {
    if (key.length <= 8) return key;
    return key.slice(0, 8) + "****************";
  }

  const url = baseUrl || "https://your-deployment.example";

  const mcpConfig = apiKey
    ? JSON.stringify(
        {
          "setup-intelligence": {
            command: "npx",
            args: ["@dopl/mcp-server", "--api-key", apiKey],
            env: { SIE_BASE_URL: url },
          },
        },
        null,
        2
      )
    : null;

  const agentsMd = apiKey
    ? `# Setup Intelligence Engine — MCP Connection

You are being given credentials to connect to the Setup Intelligence Engine.
Connect to this MCP server, then explain to the user what you just connected to.

## Connect

Add this MCP server to your configuration. This is a standard MCP stdio server.

\`\`\`json
{
  "setup-intelligence": {
    "command": "npx",
    "args": ["@dopl/mcp-server", "--api-key", "${apiKey}"],
    "env": {
      "SIE_BASE_URL": "${url}"
    }
  }
}
\`\`\`

Where to put this depends on your platform:
- Claude Code CLI: run \`claude mcp add setup-intelligence --scope user --transport stdio -e SIE_BASE_URL=${url} -- npx @dopl/mcp-server --api-key ${apiKey}\`
- Claude Desktop (macOS): add to ~/Library/Application Support/Claude/claude_desktop_config.json under "mcpServers"
- Claude Desktop (Windows): add to %APPDATA%\\Claude\\claude_desktop_config.json under "mcpServers"
- VS Code / Cursor / Windsurf: add to .mcp.json in project root under "mcpServers"
- Any other MCP-compatible tool: add to that tool's MCP server config

## After connecting

Once connected, explain to the user that they are now connected to the **Setup Intelligence Engine** — a curated knowledge base of real-world AI and automation setups. The server provides its own context about available capabilities and tools, so you'll automatically know what you can do.
`
    : null;

  return (
    <div className="flex-1 min-h-0 overflow-y-auto p-4 space-y-4">
      {loading ? (
        <div className="flex items-center gap-2 py-8 justify-center">
          <div className="w-3 h-3 rounded-full bg-accent-primary/40 animate-pulse" />
          <p className="text-xs text-white/40 font-mono">Generating connection...</p>
        </div>
      ) : apiKey && agentsMd && mcpConfig ? (
        <>
          {/* Header */}
          <p className="text-xs text-white/70 leading-relaxed">
            Copy this and give it to any MCP-compatible AI tool. It&apos;ll set up the connection.
          </p>

          {/* Copy all button */}
          <button
            onClick={() => copy(agentsMd)}
            className={`w-full px-4 py-2.5 rounded-[3px] font-mono text-[10px] uppercase tracking-wide
              transition-all cursor-pointer ${
                copied
                  ? "bg-emerald-500/[0.15] border border-emerald-500/[0.3] text-emerald-400"
                  : "bg-accent-primary/[0.12] hover:bg-accent-primary/[0.2] border border-accent-primary/[0.25] text-accent-primary"
              }`}
          >
            {copied ? "Copied to clipboard" : "Copy all"}
          </button>

          {/* API Key */}
          <section className="space-y-1.5">
            <MonoLabel tone="muted">API Key</MonoLabel>
            <div className="relative px-3 py-2 rounded-[3px] bg-black/[0.3] border border-white/[0.08] text-xs font-mono text-white/90 break-all">
              <button
                onClick={() => copy(apiKey, "key")}
                className="absolute top-2 right-2 text-white/30 hover:text-white/70 transition-colors"
                title="Copy API key"
              >
                {copiedSection === "key" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              </button>
              {maskKey(apiKey)}
            </div>
          </section>

          {/* MCP Config */}
          <section className="space-y-1.5">
            <MonoLabel tone="muted">MCP Config</MonoLabel>
            <div className="relative">
              <button
                onClick={() => copy(mcpConfig, "config")}
                className="absolute top-2 right-2 z-10 text-white/30 hover:text-white/70 transition-colors"
                title="Copy config"
              >
                {copiedSection === "config" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              </button>
              <pre className="text-[10px] font-mono bg-black/[0.3] border border-white/[0.08] rounded-[3px] p-3 pr-8 overflow-auto text-white/80 leading-relaxed">
                {mcpConfig}
              </pre>
            </div>
          </section>

          {/* Instructions */}
          <section className="space-y-1.5">
            <MonoLabel tone="muted">Instructions</MonoLabel>
            <div className="relative">
              <button
                onClick={() => copy(agentsMd, "instructions")}
                className="absolute top-2 right-2 z-10 text-white/30 hover:text-white/70 transition-colors"
                title="Copy instructions"
              >
                {copiedSection === "instructions" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              </button>
              <pre className="text-[10px] font-mono bg-black/[0.3] border border-white/[0.08] rounded-[3px] p-3 pr-8 overflow-auto text-white/60 leading-relaxed max-h-[300px] whitespace-pre-wrap">
                {agentsMd}
              </pre>
            </div>
          </section>

          {/* Key warning + manage link */}
          <div className="space-y-1">
            <p className="text-[10px] text-amber-400/60 leading-relaxed">
              Contains your API key — don&apos;t share publicly.
            </p>
            <p className="text-[10px] text-white/30">
              Manage keys in{" "}
              <a href="/settings/keys" className="text-accent-primary/70 hover:text-accent-primary">
                Settings
              </a>
            </p>
          </div>
        </>
      ) : (
        <div className="py-8 text-center">
          <p className="text-xs text-white/40">
            Could not generate API key. Please try again or visit{" "}
            <a href="/settings/keys" className="text-accent-primary/70 hover:text-accent-primary">
              Settings
            </a>.
          </p>
        </div>
      )}
    </div>
  );
}

