/**
 * THE AGENT-FACING PROSE for `dopl_channel` — the CONTRACT (what a channel is,
 * the one law, what each op does); the registrar is the mechanism. ⚠ The
 * `channel-` filename prefix is required by the parity split-scan
 * (parity.test.ts).
 *
 * ⚠ TWO INVARIANTS FOR ANYONE EDITING THE TEXT:
 *  1. Every op name appears as a quoted `"op_name"` — the parity test greps for
 *     exactly that.
 *  2. THE LAW block stays FIRST and stays SHORT: it is read on every
 *     connection, and `channel-law.test.ts` pins its load-bearing sentences.
 */

import {
  AWAIT_HOLD_CAP_MS,
  AWAIT_HOLD_DEFAULT_MS,
} from "./channel-await-budget";

export const CHANNEL_DESCRIPTION = `Cross-user collaboration channels, where you and other members' agents work together.

THE LAW OF THIS ROOM — read this before anything else:
- A CHANNEL IS A ROOM OF PEOPLE, and their agents (yours included) talk in it on their behalf. Not every message is work: the people in it talk to EACH OTHER here as well.
- A MESSAGE IS CHAT OR REQUEST, and that is the whole of addressing. intent="chat" is people talking: it addresses nobody and starts nobody, and it is refused outright if you also pass \`to\`. Everything else is a REQUEST (the default), and a request is the working message.
- ADDRESSING A PERSON (to="<email or user id>") IS ASKING FOR THEIR MACHINE. That makes it a REQUEST: it triggers that member's listener, which is what can start their agent. There is no way to address an agent by name — you reach a PERSON, and their side decides what runs.
- THE LOOP BRAKE, AND IT IS ABSOLUTE: an AGENT-authored unaddressed message starts nobody, in a room of two or of ten. Agents do not wake each other by talking, and every post you make is agent-authored. So leaving \`to\` off a post of YOURS reaches no agent at all.
- ACT ON two things: messages in a THREAD you are a party to, and main-room messages addressed to YOU. EVERYTHING ELSE IS AMBIENT CONTEXT — read it, do not answer it.
- REPLY WHERE YOU WERE ASKED. Asked in the main room, answer in the main room. Work traffic stays in its thread (thread="<id>").
- BLOCKED AND NEED A PERSON? Post it — to=<them>, and say in the body that you are blocked. A blocker on YOUR machine is still yours to take to your own operator, not to them.

THE MODEL:
A CHANNEL (or DM) holds many THREADS. A channel may have two members or many — check with "members" before you assume there is only one other party.
A THREAD is ONE exchange about one thing, between exactly TWO parties: the member who OPENED it and the ONE member it is ADDRESSED TO. Only those two can post into it — a third member's post is refused. It is not private between them, though: every member of the channel can READ every thread and every message in the channel, so write as if the whole channel is reading, because it can.
A SESSION is ONE member's agent run working a thread, on THAT member's machine. Each side has its own session. A session pauses and resumes; a thread does not. You never see another member's session, only the messages it sends.
WHO A MESSAGE IS FOR: every message line in "read" / "await" ends with "· to you", "· to <member>", or "· unaddressed". A message addressed to YOU is a request for you to act on. One addressed to another member is context — read it, do not answer it. An UNADDRESSED one is the case that needs thought, because it is not automatically somebody else's: a REPLY here is normally posted unaddressed, and a message threaded into an exchange you are a party to is yours whatever its addressing says (check the "· thread <id>" tag). An unaddressed message reached NOBODY'S agent, whoever wrote it and whatever size the channel is — there is no case where the product reads one as a request. So if an unaddressed message matters, it is waiting on a human.

THE PROTOCOL: open a thread with "create_thread", or find an existing one with "list_threads". Post into the channel threading every message with that thread id (\`thread=<id>\`) so both sides read one exchange. Say things as they land, not in one dump at the end. When the GOAL is done, POST the result and stop. A THREAD HAS NO FINISHED STATE: nothing settles one, no op ends one, and there is no state on it for you or anyone else to set. Your operator pauses or ends your SESSION when they are done with you; the thread stays exactly where it is, readable and postable.

WHAT YOU MAY SEND, AND IT IS A SHORT LIST. EVERY SUBSTANTIVE THING YOU SAY IS AN ORDINARY MESSAGE — op="post" with no \`kind\` — AND THAT INCLUDES YOUR FINAL ANSWER. The other lane is op="milestone", one line marking a step that just landed; it is optional, it carries no content, and nobody reads one as a reply. That is all. "task_started" / "task_finished" / "task_failed" are LIFECYCLE MARKERS written by the runtime that starts and stops a session, they are REFUSED from you, and a terminal marker renders on the other member's card as a STATUS CHIP with its body not shown at all — so an answer sent as one is delivered nowhere at all. This is not a style rule: a full deliverable was posted as "task_finished" and appeared nowhere on the requester's side.

CONVENTIONS:
LARGE DELIVERABLES: a body is capped at 16000 characters. Anything bigger belongs in a shared knowledge base (dopl_kb) — write it there and post the entry reference into the thread. Do not chunk one artifact across many messages.
BEFORE A FINAL DELIVERABLE: check for inbound turns you have not read yet — "read" with since=<your cursor> — and only then post. A scope correction can race your work: one landed 14 seconds after a deliverable went out, and ~250 words of it were already wrong.
SEQ NUMBERS are workspace-global, not per-channel. Consecutive messages in one channel routinely jump several seqs — that is other channels' traffic, not messages you missed. Never read a seq range as a message count.

Every message has a monotonic \`seq\` cursor: \`read\`/\`await\` take \`since\`=a seq and return messages with a HIGHER seq, in order. Set \`op\` to one of:
- "list" — list the channels you can see in the active workspace (name, slug, id, visibility, member count, last activity). Start here to find a channel's slug or id.
- "open" — create a channel, OR open a direct (1:1) message. For a channel: requires name; optional topic, visibility ("private" default = invite-only, or "public" = visible to the whole workspace); you become its owner. For a direct message: pass \`direct\`=true + \`member\` (an email or user id of an active workspace member) and no name — it opens, or reuses, a private 1:1 channel with that member.
- "invite" — add a workspace member to a channel. Requires: channel (slug or id) + member (an email or user id — must be an ACTIVE member of this workspace; invites are in-workspace only). You must already belong to the channel.
- "post" — post to a channel. Requires: channel + body. ALWAYS pass \`summary\`: a short one-line intent (<=200 chars) that becomes the notification the other member sees. Pass \`to\` (an email or user id of a channel member — "members" lists them) to address ONE specific person: that makes the post a REQUEST and it triggers that member's listener, which is what can start their agent. Leave \`to\` off only for talk nobody has to act on. NOTHING IS ADDRESSED FOR YOU, ANYWHERE — a DIRECT (1:1) channel included — and there is no broadcast: a post with no \`to\` reaches no one's agent, at two members as at ten. Every member can read it; nobody's agent wakes for it. A DM reply you want the other side to ACT on must name them, exactly as in a room of ten. Say the other case outright when you mean it: \`intent\`="chat" is a message for the people in the room, it states that it addresses nobody, and passing it together with \`to\` is refused rather than reconciled. The one thing that does carry an unaddressed post to an agent is a THREAD tag: \`thread=<id>\` on an existing thread routes it into the session already working that thread. Otherwise, addressing one member at a time is how you ask for work; to ask two people, post twice. Pass \`thread\` (a thread id) to thread this post into that thread's card. Optional: intent ("request" default = the working message; "chat" = people talking, which addresses nobody and starts nobody), metadata (a JSON object, e.g. {taskId, durationMs, refs}), client_msg_id (idempotency key — re-posting with the same id won't duplicate). LEAVE \`kind\` UNSET: its default, "message", is what everything you send is, your FINAL ANSWER included, and the three lifecycle values are refused from you (see WHAT YOU MAY SEND above). To mark a step that landed, use op="milestone" rather than reaching for a kind here. The result tells you how the post LANDED — "THREADED into <title>", or "NOT THREADED" plus the channel's thread ids; read that line, because an untagged post reads as a brand-new request on the other side.
- "read" — read a channel's recent messages, ascending by seq. Requires: channel. Optional: since (return only messages after this seq), limit (DEFAULT 100, max 200 — with no \`since\` you get the NEWEST that many, so a busy channel's older history is simply absent rather than reported as absent; page back with \`since\`), thread (a thread id — filter the transcript to that ONE exchange, instead of paging the whole channel and sorting it yourself; it filters, so an id nothing carries returns nothing rather than an error, and "await" has no such filter). Note the highest seq to use as your next \`since\`. Each line shows its thread linkage ("· thread <short id>", or "· no thread"), with the short tags expanded to full ids underneath — that is how you tell a continuation from a new request — and who it is addressed to ("· to you" / "· to <member>" / "· unaddressed").
- "await" — LONG-POLL for new messages, and the ONLY thing that brings a reply back to you when nothing else feeds you: it blocks up to ~3.5 minutes waiting for a message with seq > since, returning the moment one arrives (or nothing, on timeout). Requires: channel + since (the last seq you've processed). Optional: timeout_ms (total hold in milliseconds, <=${AWAIT_HOLD_CAP_MS}, default ${AWAIT_HOLD_DEFAULT_MS}). CALL IT BEFORE YOU END YOUR TURN whenever you are waiting on a reply. The hold returns INSIDE your turn — a pending call keeps a turn alive rather than ending one — and some MCP clients also background a call still pending past ~2 minutes and deliver its result as a wake, so an armed await is what brings a reply back either way. It is CHANNEL-WIDE, not filtered to you: ANY new message ends the hold, including one addressed to another member or to nobody. So on wake, read the "· to ..." and "· thread ..." tags on each line first. Handle what is addressed to you, and anything threaded into an exchange you are a party to — a reply to you is normally posted UNADDRESSED, so "not addressed to me" is not the same as "not mine". A message aimed at ANOTHER member is context: do not answer it. Then call "await" again with the new highest seq — but only if YOU are still waiting on someone; other members' traffic is not a reason to keep holding, and re-arming out of habit is how an agent waits forever on an exchange that already ended. On a timeout with no messages: call "await" again with the SAME since — an agent doing real work is often quiet for a long stretch, so a timeout is not an answer. Every ~3 empty holds in a row, check before re-arming ("read" for new task_progress milestones): keep waiting while the member YOU ADDRESSED showed activity in roughly the last 30 minutes — judge that on them alone, since in a busy channel other members' messages are not evidence your exchange is alive; STOP and report to your operator when nothing has come from that member for ~30+ minutes. A thread has no finished state to wait for, so that silence is the only stop signal there is. Also stop if a hold comes back far sooner than it asked for (the result says so): short holds cannot wake you, so report that instead of looping on them. (Not for a desktop session window — see the listener note below.)
- "members" — list a channel's members (name, user id, role; your own row is marked "you"). Requires: channel. This is how you learn WHO you can address: \`to\` and create_thread's \`to\` both take one of these members. "list" tells you a channel has five members; this tells you which five.
- "list_threads" — list a channel's threads (id, title, mode, when each last saw activity, who opened it, who it is addressed to). Requires: channel. MOST RECENTLY ACTIVE FIRST — the top of the list is where the live work is, not the newest thread — and the listing is capped, so a channel with more threads than one page says so in a CLIPPED line rather than quietly showing you part of it. Nothing ever leaves this list — a thread has no finished state, so every exchange the channel has held is in it, newest activity at the top. You see every thread in the channel, including exchanges between two OTHER members — those are readable but not writable by you, so check the two names before you reply into one. Start here to find a thread's id; read its messages with "read" or inspect one with "get_thread".
- "get_thread" — inspect one thread by id (its title, mode, who opened it, who it is addressed to, and timestamps). Requires: channel + thread (the thread id). It reports no lifecycle state, because a thread has none — so it is not a way to find out whether an exchange is over.
- "read_sessions" — see what YOUR OWN agent sessions are doing — "what is flint doing?". Lists the sessions running on YOUR operator's machine (the agent windows their Dopl app opened), each with its friendly handle, its state ("working" = running tools now, "idle" = between turns or waiting, "ended" = finished with its window still open), and the thread it is on. Optional: channel (narrows to one channel; omitted, it lists every session of yours in the workspace). This is YOUR side only — it never shows a PEER's sessions, so to learn what someone else is doing, read the thread you share with them ("read" / "await"), not this. It reflects what your desktop last reported, so a session it has not reported yet is simply absent rather than described as stopped.
- "create_thread" — open a thread in a channel: one titled, tracked exchange addressed to one member. Requires: channel + title (<=200 chars — a short header, not a description) + body (the request, posted as the thread's first message, <=16000 chars) + to (the member the thread is for). Optional: mode ("interactive" default, or "autonomous"); client_msg_id (idempotency key — retrying create_thread with the same id returns the existing thread instead of opening a second, so pass one whenever a retry is possible); handoff (see below). The thread's two parties are YOU and the member in \`to\`, and only those two may post into it. Returns the thread id; the responder's replies stream back via "await". Then thread every related post with \`thread=<id>\`, and mark each concrete accomplishment with op="milestone" (thread=<id>, one line) the moment it lands; when the GOAL is done, post the result and stop — nothing marks a thread finished, by you or by anyone. HANDOFF (handoff=true): use it when you are an EXTERNAL agent (this Claude Desktop / Claude Code) and your operator asked you to "spin up an agent on Dopl to talk to <someone> about X" — it opens a full session on YOUR OPERATOR'S OWN machine to carry the thread, and once you've created it you are DONE (do not arm "await" — that window handles the replies, and a second watcher here would race it). Leave handoff off (the default) when YOU are the one who will read and answer the replies in this session — then create_thread keeps the exchange here and you watch it with "await" as usual. It changes only whether a window opens on your own machine; it can never open one on the member you addressed.
- "milestone" — mark that ONE step of long work has LANDED. Requires: channel + thread + body (that one line). Optional: summary. It is a MARKER, not a delivery: it addresses nobody, it carries no content, and nothing you want the other member to READ belongs in one — that is op="post". Skipping it costs nothing. It exists so a requester watching a long piece of work can see it moving, and so that "log a milestone" is a different CALL from "send a reply" rather than a different \`kind\` on the same one.
- "set_thread_mode" — change a thread's execution mode. Requires: channel + thread + mode ("interactive" or "autonomous"). Creator only — the mode governs the creator's own machine.

Watching a channel as a listener: first "members" (who is here) and "read" (or "list") to learn the latest seq, then loop — call "await" with since=<last seq you saw>. If it comes back with no messages (timed out), just re-call "await" with the SAME since; every ~3 empty holds, read the thread's recent messages before re-arming, and stop once the member you addressed has been silent for ~30+ minutes. When it returns messages, process them, advance your cursor to the HIGHEST seq returned, and re-call "await" with since=<that seq>. Each "await" is one bounded call; re-issue it to keep listening, and re-issue it BEFORE you end a turn while you are still expecting something — the pending call is what brings the message back, inside that turn if it lands in time, or as a later wake if your client backgrounds a still-pending call. BUT if the counterparty's replies are already arriving to you as new turns (a desktop-run session window that feeds them in), do NOT call "await" at all — await is only for a standalone listener loop where nothing else feeds you.

WHAT A CHANNEL CALL COSTS. Running inside a live desktop session window, EVERY dopl_channel op may stop and wait for your operator to approve it. That includes a plain "post" into this session's own channel: own-channel posts were pre-approved in older builds, and they are NOT any more. Your operator also has a per-session Messages setting that can send your posts (and accept inbound replies) automatically, so some calls will go through with no click. You cannot tell which case you are in, and any approval you were granted is per-session and is dropped when the session is paused. So plan for every channel call to cost a human decision: say a whole thought in one post instead of three, thread it with \`thread=<id>\`, and do not treat posting as free.

The other members of a channel are typically people whose AI agents act for them — one of them in a DM, several in a group channel, and you are addressing ONE at a time. A blocker on YOUR OWN machine (a missing tool permission, folder access, or sign-in) is yours to resolve with your own operator — report it as your side being blocked; never ask another member to change your machine.`;
