// THE CODEX APP-SERVER COMPATIBILITY SUITE — U1's contract, in two tiers.
//
// 🔒 ⚠ **TIER 1 (ALWAYS RUNS) MEASURES DOPL. TIER 2 (OPT-IN) MEASURES CODEX.** They are not
// interchangeable and this file never lets one stand in for the other. Tier 1 proves the GATE's
// own logic — what `client.js › checkProtocol` does with a declared method list, with no list at
// all, with extra members — using inputs that are labelled HYPOTHETICAL at every use. Tier 2 is
// the only thing here that touches a real `codex`, and it is the only thing allowed to say what
// the protocol IS.
//
// 🔒 ⚠ **NOTHING IN TIER 1 IS A CLAIM ABOUT THE WIRE.** The plan's whole cause of death was 94
// tests green against synthetic fixtures (`docs/plans/2026-09-21-001-fix-codex-runtime-parity-plan.md`,
// research table, `Tests` row). A hypothetical input here is a function argument, never a
// transcript: it exercises a branch of Dopl's own code and asserts nothing about what OpenAI
// sends. The checked-in fixture ships as `UNVERIFIED-PLACEHOLDER` and tier 1's first test is that
// it has not been quietly hand-filled.
//
// ⚠ **OPT-IN, THE `RLS_REDTEAM_LIVE=1` WAY** (repo `CLAUDE.md`, gate 11): `CODEX_APP_SERVER_LIVE=1`.
// Mandatory in `npm run test:codex-compat`, which refuses to report success when the tier skipped.
//
//   ordinary unit run   npm test                                   (tier 2 skips, loudly)
//   with a Codex CLI    CODEX_APP_SERVER_LIVE=1 npm test           (tier 2 runs)
//   the release gate    npm run test:codex-compat                  (tier 2 is required)
//   regenerate fixture  npm run codex:schema

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';

import {
  client, LIVE_ENV, REGENERATE_CMD,
  liveGate, announceGate, skipLive,
  readFixture, fixtureIsMeasured,
  withAppServer, handshake, spawnSilentServer, leakedPids,
} from './_codex-app-server.mjs';

const GATE = announceGate(liveGate());
const FIXTURE = readFixture();
const S = client.PROTOCOL_STATE;

// ⚠ EVERY OBJECT BELOW IS A FUNCTION ARGUMENT, NOT A TRANSCRIPT. `hypothetical()` exists so that
// nothing in this file can be mistaken for a captured wire shape by a later reader or a grep.
const hypothetical = (value) => value;

// ══ TIER 1 — THE GATE'S OWN LOGIC, AND THE FIXTURE'S PROVENANCE ═════════════════════════════

describe('the fixture cannot lie about where it came from', () => {
  test('a placeholder fixture claims NO measurement — no version, no timestamp, no shapes', () => {
    if (fixtureIsMeasured(FIXTURE)) return; // the measured case is asserted below
    assert.equal(FIXTURE.status, 'UNVERIFIED-PLACEHOLDER');
    // 🔒 THE ANTI-HAND-FILL ASSERTION. A placeholder that carries a version number is a synthetic
    // fixture wearing a measurement's costume — the single failure this unit exists to prevent.
    assert.equal(FIXTURE.cli.version, null, 'a placeholder must not name a CLI version');
    assert.equal(FIXTURE.capturedAt, null, 'a placeholder must not carry a capture timestamp');
    assert.equal(FIXTURE.generatedBy, null, 'a placeholder was generated by nothing');
    for (const key of ['initialize', 'declaredMethods', 'modelList']) {
      assert.equal(FIXTURE.handshake[key], null, `a placeholder must not hold a ${key} shape`);
    }
    assert.match(FIXTURE.statusNote, /NOTHING IN THIS FILE WAS MEASURED/);
  });

  test('a MEASURED fixture carries its CLI version, its timestamp and its generator', () => {
    if (!fixtureIsMeasured(FIXTURE)) return;
    assert.ok(FIXTURE.cli.version, 'a measured fixture names the CLI version it came from');
    assert.ok(FIXTURE.capturedAt, 'a measured fixture names when it was captured');
    assert.match(FIXTURE.generatedBy, /codex-app-server-schema\.js$/);
    assert.ok(FIXTURE.handshake.initialize, 'a measured fixture holds an initialize shape');
    // 🔒 A MEASURED FIXTURE MUST NAME ITS BINARY, because a binary inside another application
    // bundle is excluded by the plan's Scope Boundaries and a reviewer has to be able to see that
    // from the fixture alone.
    assert.ok(FIXTURE.cli.path, 'a measured fixture names the file it measured');
  });

  test('a MEASURED fixture declares every method Dopl sends, or it is not a supported CLI', () => {
    if (!fixtureIsMeasured(FIXTURE)) return;
    const declared = FIXTURE.handshake.declaredMethods;
    assert.ok(declared, 'the CLI must enumerate its methods — `generate-json-schema` is the source');
    const have = new Set(declared.names);
    const absent = client.REQUIRED_METHODS.filter((m) => !have.has(m));
    assert.deepEqual(absent, [], `this CLI does not offer ${absent.join(', ')}`);
  });

  test('the fixture states the one command that regenerates it', () => {
    assert.equal(FIXTURE.regenerate, REGENERATE_CMD);
  });

  test('`doplRequires` has not drifted from the gate it mirrors', () => {
    // ⚠ NOT A PROTOCOL CLAIM — it is Dopl's own requirement, and the fixture carries a copy so a
    // reviewer reading the fixture alone sees what the suite will demand of their CLI.
    assert.deepEqual(FIXTURE.doplRequires.methods, client.REQUIRED_METHODS.slice());
    assert.deepEqual(FIXTURE.doplRequires.facts, client.REQUIRED_FACTS.map((f) => f.key));
  });
});

describe('the compatibility gate separates missing, signed-out and unsupported', () => {
  test('the four states are four distinct strings', () => {
    const values = Object.values(S);
    assert.equal(new Set(values).size, values.length);
    assert.equal(S.UNSUPPORTED, 'unsupported-protocol');
    assert.notEqual(S.UNSUPPORTED, S.MISSING);
    assert.notEqual(S.UNSUPPORTED, S.SIGNED_OUT);
  });

  test('a server that declares everything Dopl needs is READY', () => {
    const verdict = client.checkProtocol(hypothetical({
      version: '0.0.0',
      methods: client.REQUIRED_METHODS.slice(),
      facts: { threadId: 'thread-1', modelDefault: 'a-model' },
    }));
    assert.equal(verdict.state, S.READY);
    assert.equal(verdict.ok, true);
  });

  test('a MISSING METHOD is `unsupported-protocol`, names the method, and is NOT connected', () => {
    for (const dropped of client.REQUIRED_METHODS) {
      const verdict = client.checkProtocol(hypothetical({
        version: '0.0.0',
        methods: client.REQUIRED_METHODS.filter((m) => m !== dropped),
        facts: { threadId: 't', modelDefault: 'm' },
      }));
      assert.equal(verdict.ok, false, `${dropped} missing must not be connected`);
      assert.equal(verdict.state, S.UNSUPPORTED);
      assert.deepEqual(verdict.missingMethods, [dropped]);
      assert.match(verdict.reason, new RegExp(dropped.replace('/', '\\/')));
    }
  });

  test('a MISSING CRITICAL FIELD is `unsupported-protocol` and says which, and why', () => {
    for (const fact of client.REQUIRED_FACTS) {
      const facts = { threadId: 't', modelDefault: 'm' };
      delete facts[fact.key];
      const verdict = client.checkProtocol(hypothetical({
        version: '0.0.0', methods: client.REQUIRED_METHODS.slice(), facts,
      }));
      assert.equal(verdict.ok, false);
      assert.equal(verdict.state, S.UNSUPPORTED);
      assert.deepEqual(verdict.missingFacts.map((f) => f.key), [fact.key]);
      assert.match(verdict.reason, new RegExp(fact.why.slice(0, 20)));
    }
    // An EMPTY STRING is a missing field, not a present one.
    const blank = client.checkProtocol(hypothetical({
      version: '0.0.0', methods: client.REQUIRED_METHODS.slice(), facts: { threadId: '', modelDefault: 'm' },
    }));
    assert.equal(blank.state, S.UNSUPPORTED);
  });
});

describe('unknown is not empty, and extra is not a failure', () => {
  test('EXTRA unknown methods are IGNORED — a newer server is not an incompatible one', () => {
    const verdict = client.checkProtocol(hypothetical({
      version: '0.0.0',
      methods: client.REQUIRED_METHODS.concat(['thread/somethingNew', 'account/whatever']),
      facts: { threadId: 't', modelDefault: 'm' },
    }));
    assert.equal(verdict.state, S.READY, 'unknown methods must not refuse a working server');
  });

  test('EXTRA unknown facts are IGNORED', () => {
    const verdict = client.checkProtocol(hypothetical({
      version: '0.0.0',
      methods: client.REQUIRED_METHODS.slice(),
      facts: { threadId: 't', modelDefault: 'm', somethingTheSchemaGrew: 42 },
    }));
    assert.equal(verdict.state, S.READY);
  });

  test('UNDECLARED (`null`) is `unverified-protocol`; DECLARED-EMPTY (`[]`) is `unsupported`', () => {
    // 🔒 `docs/INVARIANTS.md`: unknown capability must stay different from an empty value. Folding
    // `null` into `[]` refuses working installs; folding it into READY restores false confidence.
    const undeclared = client.checkProtocol(hypothetical({ version: '0.0.0', methods: null, facts: { threadId: 't', modelDefault: 'm' } }));
    assert.equal(undeclared.state, S.UNVERIFIED);
    assert.equal(undeclared.ok, false, 'unverified is never connected');
    assert.deepEqual(undeclared.missingMethods, []);

    const empty = client.checkProtocol(hypothetical({ version: '0.0.0', methods: [], facts: { threadId: 't', modelDefault: 'm' } }));
    assert.equal(empty.state, S.UNSUPPORTED);
    assert.deepEqual(empty.missingMethods, client.REQUIRED_METHODS.slice());
  });

  test('no handshake at all is `unverified-protocol`, not `ready` and not `unsupported`', () => {
    const verdict = client.checkProtocol(hypothetical({ version: '0.0.0', methods: client.REQUIRED_METHODS.slice(), facts: null }));
    assert.equal(verdict.state, S.UNVERIFIED);
    assert.match(verdict.reason, /no handshake was run/);
  });
});

describe('the model catalog must declare exactly one default', () => {
  const rows = (...flags) => flags.map((isDefault, i) => ({ id: `m-${i}`, isDefault }));

  test('exactly one default is READY and names it', () => {
    const verdict = client.catalogGate(hypothetical(rows(false, true, false)));
    assert.equal(verdict.ok, true);
    assert.deepEqual(verdict.defaults, ['m-1']);
  });

  test('zero and two defaults are both `unsupported-protocol`, with a countable reason', () => {
    assert.equal(client.catalogGate(hypothetical(rows(false, false))).state, S.UNSUPPORTED);
    const two = client.catalogGate(hypothetical(rows(true, true)));
    assert.equal(two.state, S.UNSUPPORTED);
    assert.match(two.reason, /declares 2 defaults/);
  });

  test('NO catalog read is `unverified`, an EMPTY catalog is `unsupported`', () => {
    assert.equal(client.catalogGate(null).state, S.UNVERIFIED);
    assert.equal(client.catalogGate([]).state, S.UNSUPPORTED);
  });

  test('the default flag is read tolerantly, because its spelling is not measured yet', () => {
    for (const key of ['isDefault', 'is_default', 'default']) {
      const verdict = client.catalogGate(hypothetical([{ id: 'x', [key]: true }, { id: 'y' }]));
      assert.equal(verdict.ok, true, key);
    }
  });
});

describe('the version gate', () => {
  test('UNPINNED refuses nothing and says so — a range nobody measured is not a refusal', () => {
    const verdict = client.versionGate('codex-cli 0.31.0');
    if (!client.SUPPORTED_CLI.min && !client.SUPPORTED_CLI.max) {
      assert.equal(verdict.verdict, 'unpinned');
      assert.equal(verdict.ok, true);
    } else {
      assert.notEqual(verdict.verdict, 'unpinned');
    }
  });

  test('a version string is parsed out of whatever the CLI prints around it', () => {
    assert.deepEqual(client.parseVersion('codex-cli 0.31.2'), [0, 31, 2]);
    assert.deepEqual(client.parseVersion('1.4'), [1, 4, 0]);
    assert.equal(client.parseVersion('no numbers here'), null);
  });
});

// ══ THE TIMEOUT PATH — a real child, bounded, killed ════════════════════════════════════════

describe('a handshake that times out kills the child and hangs nothing', () => {
  test('the bounded helper rejects, and the silent child is dead afterwards', async () => {
    // ⚠ THE CHILD SAYS NOTHING. It is a `node` that holds stdin open — a timeout fixture, not a
    // protocol fixture, so it invents no wire shape.
    let pid = null;
    await assert.rejects(
      withAppServer({ timeoutMs: 250, connect: () => { const c = spawnSilentServer(); pid = c.child.pid; return c; } }, (conn) => conn.request('initialize', {})),
      /did not answer within 250ms/,
    );
    assert.ok(pid, 'the fixture child started');
    let stillThere = true;
    try { process.kill(pid, 0); } catch (_) { stillThere = false; }
    assert.equal(stillThere, false, 'the child must be dead once the bounded call returned');
  });

  test('a throw inside the bounded call still kills the child', async () => {
    let pid = null;
    await assert.rejects(
      withAppServer({ timeoutMs: 5000, connect: () => { const c = spawnSilentServer(); pid = c.child.pid; return c; } }, () => { throw new Error('boom'); }),
      /boom/,
    );
    let stillThere = true;
    try { process.kill(pid, 0); } catch (_) { stillThere = false; }
    assert.equal(stillThere, false);
  });

  test('the helper leaked nothing', () => {
    assert.deepEqual(leakedPids(), []);
  });
});

// ══ THE SKIP ITSELF IS TESTED ═══════════════════════════════════════════════════════════════

describe('a skipped live tier cannot read as a passing one', () => {
  test('an unset flag is not armed, and the reason names the flag', () => {
    const gate = liveGate({});
    assert.equal(gate.armed, false);
    assert.match(gate.reason, new RegExp(LIVE_ENV));
  });

  test('ARMED WITH NO BINARY is a refusal the release command can see', () => {
    // ⚠ The release command calls `liveOrThrow`, so "you asked for live and nothing ran" fails
    // rather than passing quietly. Here we only assert the gate reports it.
    const gate = liveGate({ [LIVE_ENV]: '1', PATH: '/nonexistent-for-this-test' });
    if (gate.armed) return; // this machine has a Codex; the negative case is unreachable
    assert.match(gate.reason, new RegExp(`${LIVE_ENV}=1 was set but no Codex binary resolved`));
  });
});

// ══ TIER 2 — THE LIVE app-server. THE ONLY TIER THAT MAY SAY WHAT THE PROTOCOL IS ═══════════

describe('live Codex app-server contract', () => {
  test('initialize answers, and the catalog declares exactly one default', async (t) => {
    if (skipLive(t, GATE)) return;
    const result = await handshake({
      timeoutMs: 30000,
      extra: (conn) => conn.request('model/list', {}),
    });
    assert.ok(result.initialize && typeof result.initialize === 'object', 'initialize returned an object');
    const rows = (result.extra && (result.extra.models || result.extra.data || result.extra.items))
      || (Array.isArray(result.extra) ? result.extra : null);
    const verdict = client.catalogGate(rows);
    assert.equal(verdict.ok, true, `model/list must declare exactly one default — ${verdict.reason}`);
  });

  test('an UNKNOWN METHOD is refused by the server and is NOT connected by the gate', async (t) => {
    if (skipLive(t, GATE)) return;
    const seen = await handshake({
      timeoutMs: 30000,
      extra: (conn) => conn.request('dopl/thisMethodDoesNotExist', {}).then(
        () => ({ refused: false }),
        (err) => ({ refused: true, code: err && err.code }),
      ),
    });
    assert.equal(seen.extra.refused, true, 'the app-server must refuse a method it does not have');
    const verdict = client.checkProtocol({
      version: GATE.bin.path, methods: ['initialize'], facts: { threadId: 't', modelDefault: 'm' },
    });
    assert.equal(verdict.ok, false);
    assert.equal(verdict.state, client.PROTOCOL_STATE.UNSUPPORTED);
  });

  test('EXTRA unknown params in initialize are ignored, not treated as empty', async (t) => {
    if (skipLive(t, GATE)) return;
    const result = await withAppServer({ timeoutMs: 30000 }, (conn) => conn.request(
      'initialize',
      Object.assign(client.initializeParams('0.0.0-test'), { doplUnknownField: { nested: true } }),
    ));
    assert.ok(result && typeof result === 'object', 'an unknown extra param must not break initialize');
  });

  test('the checked-in fixture matches this CLI — otherwise REGENERATE it', async (t) => {
    if (skipLive(t, GATE)) return;
    assert.equal(
      fixtureIsMeasured(FIXTURE), true,
      `the fixture is still ${FIXTURE.status}. A live CLI is present, so measure it: ${REGENERATE_CMD}`,
    );
    const live = await handshake({ timeoutMs: 30000 });
    assert.ok(live.initialize);
    assert.ok(FIXTURE.cli.version, 'the measured fixture names a version');
  });

  test('the live tier leaked no app-server processes', (t) => {
    if (skipLive(t, GATE)) return;
    assert.deepEqual(leakedPids(), []);
  });
});
