import { z } from "zod";
import {
  DEFAULT_MESSAGE_LIMIT,
  MAX_AWAIT_TIMEOUT_MS,
  MAX_MESSAGE_LIMIT,
} from "./constants";

const VisibilitySchema = z.enum(["private", "public"]);
// `system` is server-reserved (joins / topic changes are generated by the
// service, never by a client): a caller must not be able to post an
// anonymized system-styled message. Agent stays postable — the desktop app
// posts task results with authorKind `agent` over a cookie session, and the
// service derives `agent` vs `user` from the token when authorKind is omitted.
const PostableAuthorKindSchema = z.enum(["user", "agent"]);
const MessageKindSchema = z.enum([
  "message",
  "task_started",
  "task_progress",
  "task_finished",
  "task_failed",
  "system",
]);

/**
 * Create a channel. `slug` is optional — the service derives one from the
 * name when omitted and resolves collisions. `visibility` defaults to
 * private (members only) in the service.
 */
export const ChannelCreateSchema = z.object({
  name: z.string().trim().min(1).max(120),
  slug: z.string().trim().min(1).max(80).optional(),
  topic: z.string().max(2000).optional(),
  visibility: VisibilitySchema.optional(),
});
export type ChannelCreateInput = z.infer<typeof ChannelCreateSchema>;

/**
 * Update a channel header. `archived` toggles the archive state
 * (stamps / clears `archived_at`). At least one field is required.
 */
export const ChannelUpdateSchema = z
  .object({
    name: z.string().trim().min(1).max(120).optional(),
    topic: z.string().max(2000).optional(),
    visibility: VisibilitySchema.optional(),
    archived: z.boolean().optional(),
  })
  .refine((patch) => Object.keys(patch).length > 0, { message: "Empty patch" });
export type ChannelUpdateInput = z.infer<typeof ChannelUpdateSchema>;

/**
 * Post a message or activity event. `body` carries the human-readable
 * render (so the thread needs no special-casing per kind); structured
 * payload rides in `metadata`. `clientMsgId` is the idempotency key.
 */
export const ChannelMessageCreateSchema = z.object({
  body: z.string().min(1).max(16000),
  kind: MessageKindSchema.optional(),
  authorKind: PostableAuthorKindSchema.optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  clientMsgId: z.string().min(1).max(200).optional(),
});
export type ChannelMessageCreateInput = z.infer<
  typeof ChannelMessageCreateSchema
>;

export const ChannelMemberAddSchema = z.object({
  userId: z.string().uuid(),
});
export type ChannelMemberAddInput = z.infer<typeof ChannelMemberAddSchema>;

export const ChannelMemberRemoveSchema = z.object({
  userId: z.string().uuid(),
});
export type ChannelMemberRemoveInput = z.infer<
  typeof ChannelMemberRemoveSchema
>;

/** `?since=<seq>&limit=<n<=200>` for a message read. */
export const MessageReadQuerySchema = z.object({
  since: z.coerce.number().int().nonnegative().optional(),
  limit: z.coerce
    .number()
    .int()
    .positive()
    .max(MAX_MESSAGE_LIMIT)
    .optional()
    .default(DEFAULT_MESSAGE_LIMIT),
});
export type MessageReadQuery = z.infer<typeof MessageReadQuerySchema>;

/** `?since=<seq>&timeoutMs<=50000` for the await long-poll. */
export const AwaitQuerySchema = z.object({
  since: z.coerce.number().int().nonnegative().optional(),
  timeoutMs: z.coerce
    .number()
    .int()
    .positive()
    .max(MAX_AWAIT_TIMEOUT_MS)
    .optional(),
});
export type AwaitQuery = z.infer<typeof AwaitQuerySchema>;
