import { z } from "zod";
import {
  DEFAULT_MESSAGE_LIMIT,
  MAX_AWAIT_TIMEOUT_MS,
  MAX_MESSAGE_LIMIT,
} from "./constants";

const VisibilitySchema = z.enum(["private", "public"]);
// `system` is server-reserved (joins / topic changes are generated by the
// service, never by a client): a caller must not be able to post an
// anonymized system-styled message. Agent stays postable — the desktop app
// posts task results with authorKind `agent` over a cookie session, and the
// service derives `agent` vs `user` from the token when authorKind is omitted.
const PostableAuthorKindSchema = z.enum(["user", "agent"]);
// `system` is server-emitted only — callers can never post it (matches the MCP
// tool's post enum, which also excludes it). The full kind union (incl.
// `system`) lives in types.ts; the schema only ever validates caller input.
const PostableMessageKindSchema = z.enum([
  "message",
  "task_started",
  "task_progress",
  "task_finished",
  "task_failed",
]);

/**
 * Create a channel. Two shapes on one endpoint (union):
 *   - normal: `{ name, slug?, topic?, visibility? }` — `slug` is optional (the
 *     service derives one and resolves collisions); `visibility` defaults to
 *     private in the service.
 *   - direct (v15): `{ direct: true, memberUserId }` — a 1:1 channel with the
 *     named member. No name/slug/topic/visibility (the service stores a
 *     placeholder name + private visibility); dedup + membership-of-2 are
 *     enforced server-side, and a self-target is rejected.
 *
 * A union (not a discriminated union) so today's `{ name }` callers keep
 * parsing unchanged: the normal branch has no discriminator to add.
 */
export const ChannelCreateSchema = z.union([
  z.object({
    direct: z.literal(true),
    memberUserId: z.string().uuid(),
  }),
  z.object({
    direct: z.literal(false).optional(),
    name: z.string().trim().min(1).max(120),
    slug: z.string().trim().min(1).max(80).optional(),
    topic: z.string().max(2000).optional(),
    visibility: VisibilitySchema.optional(),
  }),
]);
export type ChannelCreateInput = z.infer<typeof ChannelCreateSchema>;

/**
 * Update a channel header. `archived` toggles the archive state
 * (stamps / clears `archived_at`). At least one field is required.
 */
export const ChannelUpdateSchema = z
  .object({
    name: z.string().trim().min(1).max(120).optional(),
    topic: z.string().max(2000).optional(),
    visibility: VisibilitySchema.optional(),
    archived: z.boolean().optional(),
  })
  .refine((patch) => Object.keys(patch).length > 0, { message: "Empty patch" });
export type ChannelUpdateInput = z.infer<typeof ChannelUpdateSchema>;

/**
 * Post a message or activity event. `body` carries the human-readable
 * render (so the thread needs no special-casing per kind); structured
 * payload rides in `metadata`. `clientMsgId` is the idempotency key.
 *
 * Addressing (v1.1): `toUserId` targets a specific channel member (the
 * service validates it is an active member, else 400) and `summary` is a
 * one-line intent used in the receiver's notification. Both are persisted
 * into `metadata` as `{to_user_id, summary}`.
 */
export const ChannelMessageCreateSchema = z.object({
  body: z.string().min(1).max(16000),
  kind: PostableMessageKindSchema.optional(),
  authorKind: PostableAuthorKindSchema.optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  clientMsgId: z.string().min(1).max(200).optional(),
  toUserId: z.string().uuid().optional(),
  summary: z.string().trim().min(1).max(200).optional(),
});
export type ChannelMessageCreateInput = z.infer<
  typeof ChannelMessageCreateSchema
>;

// ─── Tasks (first-class channel tasks, v15) ─────────────────────────────────

/** Task execution mode. `set_task_mode` governs the creator's own machine. */
const TaskModeSchema = z.enum(["interactive", "autonomous"]);

/** How a closed task ended. */
const TaskOutcomeSchema = z.enum(["completed", "failed"]);

/**
 * Create a task in a channel. `title` is the queryable header; `body` is the
 * requester's initial request (posted as the task's first message, addressed
 * to `toUserId`); `mode` defaults to interactive. `toUserId` must be an active
 * member of the channel (validated in the service).
 */
export const TaskCreateSchema = z.object({
  title: z.string().trim().min(1).max(200),
  mode: TaskModeSchema.optional(),
  body: z.string().min(1).max(16000),
  toUserId: z.string().uuid(),
});
export type TaskCreateInput = z.infer<typeof TaskCreateSchema>;

/**
 * Update a task: close it (`op:"close"` — creator or target) OR change its
 * mode (`op:"set_mode"` — creator only). A discriminated union so the two
 * ops can't bleed fields into each other.
 */
export const TaskUpdateSchema = z.discriminatedUnion("op", [
  z.object({ op: z.literal("close"), outcome: TaskOutcomeSchema }),
  z.object({ op: z.literal("set_mode"), mode: TaskModeSchema }),
]);
export type TaskUpdateInput = z.infer<typeof TaskUpdateSchema>;

/** Per-member notification scope for a channel (self-service preference). */
const NotifyScopeSchema = z.enum(["all", "addressed", "none"]);

/** Per-member responding-agent tool scope (self-service preference). */
const AgentToolProfileSchema = z.enum(["full", "dopl_only", "read_only"]);

/**
 * PATCH /members body: a member updating their OWN per-channel preferences —
 * notify scope and/or agent tool profile. At least one field is required (an
 * empty patch is a no-op the route rejects). Both are self-only: the service
 * always targets the caller's row.
 */
export const ChannelMemberSelfUpdateSchema = z
  .object({
    notifyScope: NotifyScopeSchema.optional(),
    agentToolProfile: AgentToolProfileSchema.optional(),
  })
  .refine((patch) => Object.keys(patch).length > 0, { message: "Empty patch" });
export type ChannelMemberSelfUpdateInput = z.infer<
  typeof ChannelMemberSelfUpdateSchema
>;

export const ChannelMemberAddSchema = z.object({
  userId: z.string().uuid(),
});
export type ChannelMemberAddInput = z.infer<typeof ChannelMemberAddSchema>;

export const ChannelMemberRemoveSchema = z.object({
  userId: z.string().uuid(),
});
export type ChannelMemberRemoveInput = z.infer<
  typeof ChannelMemberRemoveSchema
>;

/** `?since=<seq>&limit=<n<=200>` for a message read. */
export const MessageReadQuerySchema = z.object({
  since: z.coerce.number().int().nonnegative().optional(),
  limit: z.coerce
    .number()
    .int()
    .positive()
    .max(MAX_MESSAGE_LIMIT)
    .optional()
    .default(DEFAULT_MESSAGE_LIMIT),
});
export type MessageReadQuery = z.infer<typeof MessageReadQuerySchema>;

/** `?since=<seq>&timeoutMs<=50000` for the await long-poll. */
export const AwaitQuerySchema = z.object({
  since: z.coerce.number().int().nonnegative().optional(),
  timeoutMs: z.coerce
    .number()
    .int()
    .positive()
    .max(MAX_AWAIT_TIMEOUT_MS)
    .optional(),
});
export type AwaitQuery = z.infer<typeof AwaitQuerySchema>;

// ─── Consent (inbound consent + outbound review) ────────────────────────────

/**
 * The triggering message's `seq`. NOT coerced: this arrives in a JSON body,
 * where `z.coerce.number()` would silently turn `null` / `""` / `[]` into 0
 * and `true` into 1 — a de-dupe key must never be manufactured out of junk.
 * (Coercion belongs on query strings, where everything is a string by
 * definition.) `seq` is a 1-based identity column, so 0 is not a real seq.
 */
const ConsentMessageSeqSchema = z.number().int().positive();

/** Fields every consent create carries, whatever the kind. */
const consentCreateBase = {
  channelId: z.string().uuid(),
  summary: z.string().trim().max(200).optional().default(""),
  bodyPreview: z.string().max(16000).optional().default(""),
};

/**
 * Create a consent request. The desktop POSTs this when a trigger fires
 * (inbound) or a reply is drafted (outbound). `operatorUserId` is NEVER in the
 * body — it is always the authenticated caller (a caller can only raise a
 * request addressed to themselves). `requesterUserId` is derived server-side
 * from the triggering message. `summary` shares the message summary's cap
 * (it renders on the card); `bodyPreview` / `proposedReply` are larger.
 *
 * A discriminated union on `kind` so the two shapes can't bleed into each
 * other: only an OUTBOUND request carries a `proposedReply` (an inbound row
 * with a drafted reply is nonsense, and accepting one let a caller pre-seed
 * the outbound review's payload). `messageSeq` is meaningful for BOTH kinds —
 * it is the de-dupe key (inbound: the triggering message; outbound: the
 * message the reply answers), so a retry can't stack duplicate cards.
 */
export const ConsentCreateSchema = z.discriminatedUnion("kind", [
  z.object({
    ...consentCreateBase,
    kind: z.literal("inbound"),
    messageSeq: ConsentMessageSeqSchema.optional(),
  }),
  z.object({
    ...consentCreateBase,
    kind: z.literal("outbound"),
    messageSeq: ConsentMessageSeqSchema.optional(),
    proposedReply: z.string().max(16000).optional(),
  }),
]);
export type ConsentCreateInput = z.infer<typeof ConsentCreateSchema>;

/**
 * Which human surface recorded the decision — persisted verbatim into
 * `decided_by` for the audit trail. The desktop's native dialog sends
 * `decidedBy: 'desktop'`; the web UI omits it and defaults to `web`.
 * `trust` is server-generated only (a standing rule, not a human click) and
 * is deliberately NOT accepted from a caller.
 */
const ConsentDecidedBySchema = z.enum(["web", "desktop"]);

/** PATCH /consent/[id] body: the operator's decision + which surface made it. */
export const ConsentDecisionSchema = z.object({
  decision: z.enum(["allow", "deny"]),
  decidedBy: ConsentDecidedBySchema.optional().default("web"),
});
export type ConsentDecisionInput = z.infer<typeof ConsentDecisionSchema>;

/**
 * Consent inbox filter. `pending` (the default, and what the web inbox
 * renders) keeps the card list to things that still need an answer;
 * `decided` is the audit view — it is the ONLY way to read the
 * `auto_allowed` rows a trust rule writes, i.e. "your agent ran N times
 * without asking"; `all` is both.
 */
const ConsentStatusFilterSchema = z.enum(["pending", "decided", "all"]);
export type ConsentStatusFilter = z.infer<typeof ConsentStatusFilterSchema>;

/** `?channelId=<uuid>&status=<pending|decided|all>` for the consent inbox. */
export const ConsentListQuerySchema = z.object({
  channelId: z.string().uuid().optional(),
  status: ConsentStatusFilterSchema.optional().default("pending"),
});
export type ConsentListQuery = z.infer<typeof ConsentListQuerySchema>;

// ─── Trust (per-teammate standing consent) ──────────────────────────────────

/** POST / DELETE /trust body: the teammate whose agent is (un)trusted. */
export const TrustMutateSchema = z.object({
  trustedUserId: z.string().uuid(),
});
export type TrustMutateInput = z.infer<typeof TrustMutateSchema>;

// ─── Presence (desktop heartbeat) ───────────────────────────────────────────

/**
 * POST /presence body: an optional status label (defaults to 'listening').
 * A closed enum, not free text — the column is rendered as a listener state
 * and a matching CHECK constraint backs it in the database, so an arbitrary
 * string can't be written through the heartbeat and then surfaced in the UI.
 */
export const PresenceHeartbeatSchema = z.object({
  status: z.enum(["listening", "busy", "paused", "offline"]).optional(),
});
export type PresenceHeartbeatInput = z.infer<typeof PresenceHeartbeatSchema>;
