import { z } from "zod";
import { safeLabel, safeOptionalLabel } from "@/shared/lib/safe-label";
import {
  DEFAULT_MESSAGE_LIMIT,
  MAX_AWAIT_TIMEOUT_MS,
  MAX_MESSAGE_LIMIT,
} from "./constants";
import type { MessageIntent } from "./types";
import { ThreadParticipantSeedSchema } from "./schema-agents";

/**
 * The multiplayer schemas (agents + thread participants) live in
 * `schema-agents.ts` for the §2 size cap and are re-exported here, so every
 * caller still imports channel request schemas from ONE module.
 */
export {
  AGENT_HANDLE_RE,
  ChannelAgentCreateSchema,
  ChannelAgentUpdateSchema,
  ThreadParticipantMutateSchema,
  ThreadParticipantRefSchema,
  ThreadParticipantSeedSchema,
} from "./schema-agents";
export type {
  ChannelAgentCreateInput,
  ChannelAgentUpdateInput,
  ThreadParticipantMutateInput,
  ThreadParticipantRef,
} from "./schema-agents";

const VisibilitySchema = z.enum(["private", "public"]);

/**
 * Q1 (write-op sweep) — CHARSET RULES FOR THE CHANNEL HEADER.
 *
 * `name` and `topic` were bounded by LENGTH ONLY (120 / 2000) and by nothing
 * else. Both are peer-authored and both are spliced into `dopl_channel` results
 * as SERVER NARRATION — the part of a tool result a model reads as the tool
 * speaking, outside the untrusted-content headers that disclaim message bodies:
 *
 *   - `name` lands in nearly every write-op line ("Posted to <name>", "Added
 *     <member> to <name>", every 400 mapping). `resolveChannelOr` resolves
 *     PUBLIC channels the caller was never invited to, so the name can come
 *     from someone the reading agent has had no contact with.
 *   - `topic` lands in `op="list"`, which the tool description tells an agent
 *     to start with, and a public channel is listed to every workspace member.
 *
 * The MCP renderers neutralize both now, and that is the layer that actually
 * has to hold. This is the second layer, for the same reason `display_name` got
 * one tonight: a route-only fence next to an open gate is not a fence, and the
 * renderers are not the only consumers (`channels-list-pane` renders the topic
 * inline, the desktop listener builds prompts from channel context). A field
 * that can never hold a newline cannot forge a line anywhere, including in
 * surfaces written later that forget to neutralize.
 *
 * SAME RULE FOR BOTH, and it is not a product restriction: the create dialog
 * offers a single-line `<input maxLength={2000}>` for the topic and renders it
 * in a `truncate` span. Multi-line topics exist only through the API — i.e.
 * only for a caller composing one deliberately.
 *
 * The rule itself now lives in `@/shared/lib/safe-label` — it was written
 * twice (here and as `DISPLAY_NAME_RE` in
 * `src/app/api/user/profile/route.ts`) and has been applied to a dozen more
 * short labels since, so it has one home. Character for character the same
 * class and the same error copy: control characters (the newline that forges a
 * line, and every other C0 / DEL byte), zero-width and bidi-override
 * characters, and the line/paragraph separators some renderers still treat as
 * newlines.
 */

/** `name` — required where it appears, trimmed, 1..120, charset-bounded. */
const ChannelNameSchema = safeLabel("Channel name", 120);

/**
 * `topic` — optional, so `""` stays legal (the create dialog sends the field
 * cleared, and the column is NOT NULL with a `''` default). `safeOptionalLabel`
 * carries the explicit empty-string branch the charset class cannot express on
 * its own: `""` carries nothing to forge with.
 */
const ChannelTopicSchema = safeOptionalLabel("Channel topic", 2000);
// `system` is server-reserved (joins / topic changes are generated by the
// service, never by a client): a caller must not be able to post an
// anonymized system-styled message. Agent stays postable — the desktop app
// posts task results with authorKind `agent` over a cookie session, and the
// service derives `agent` vs `user` from the token when authorKind is omitted.
const PostableAuthorKindSchema = z.enum(["user", "agent"]);
// `system` is server-emitted only — callers can never post it (matches the MCP
// tool's post enum, which also excludes it). The full kind union (incl.
// `system`) lives in types.ts; the schema only ever validates caller input.
const PostableMessageKindSchema = z.enum([
  "message",
  "task_started",
  "task_progress",
  "task_finished",
  "task_failed",
]);

/**
 * Create a channel. Two shapes on one endpoint (union):
 *   - normal: `{ name, slug?, topic?, visibility? }` — `slug` is optional (the
 *     service derives one and resolves collisions); `visibility` defaults to
 *     private in the service.
 *   - direct (v15): `{ direct: true, memberUserId }` — a 1:1 channel with the
 *     named member. No name/slug/topic/visibility (the service stores a
 *     placeholder name + private visibility); dedup + membership-of-2 are
 *     enforced server-side, and a self-target is rejected.
 *
 * A union (not a discriminated union) so today's `{ name }` callers keep
 * parsing unchanged: the normal branch has no discriminator to add.
 */
export const ChannelCreateSchema = z.union([
  z.object({
    direct: z.literal(true),
    memberUserId: z.string().uuid(),
  }),
  z.object({
    direct: z.literal(false).optional(),
    name: ChannelNameSchema,
    slug: z.string().trim().min(1).max(80).optional(),
    topic: ChannelTopicSchema.optional(),
    visibility: VisibilitySchema.optional(),
  }),
]);
export type ChannelCreateInput = z.infer<typeof ChannelCreateSchema>;

/**
 * Update a channel header. `archived` toggles the archive state
 * (stamps / clears `archived_at`). At least one field is required.
 */
export const ChannelUpdateSchema = z
  .object({
    name: ChannelNameSchema.optional(),
    topic: ChannelTopicSchema.optional(),
    visibility: VisibilitySchema.optional(),
    archived: z.boolean().optional(),
  })
  .refine((patch) => Object.keys(patch).length > 0, { message: "Empty patch" });
export type ChannelUpdateInput = z.infer<typeof ChannelUpdateSchema>;

/**
 * CHAT vs. REQUEST — whether a post is allowed to reach anybody's agent.
 *
 * The operator's report, verbatim: *"if I send a message it's just going as a
 * message to the channel... doesn't prompt an agent."* It was the opposite. In
 * a DM the server AUTO-ADDRESSES every post to the peer (v2.6, and for a good
 * reason — an unaddressed agent reply is deliberately ignorable, so a real
 * reply was posting successfully and never being delivered). The cost of that
 * fix was that two HUMANS could not talk in a DM without poking each other's
 * machines: every "sounds good" addressed the peer and raised a consent prompt.
 *
 * So intent is now first-class rather than inferred:
 *  - `request` (the DEFAULT, and what every existing caller gets) — today's
 *    behaviour, byte for byte. The DM auto-address still fires, `to` / `toAgent`
 *    still address, and the receiving listener still triggers.
 *  - `chat` — HUMAN TALK. The DM auto-address is SKIPPED ENTIRELY: no
 *    `to_user_id` is manufactured from the peer, so nothing on the far side
 *    classifies an aside as an ask. Everything else about the post is normal
 *    (seq, realtime, read watermark, an explicit `thread` tag if the caller
 *    passes one).
 *
 * `chat` WITH `toAgent` / `toAgents` is ALLOWED, and is the PRIMARY way an agent
 * is given work: "@quartz @onyx work together on X" typed into the composer is a
 * human talking in the room and naming who should act. The addressed agents are
 * stamped, engaged, and reached through the owner bridge; nobody else is.
 *
 * `chat` WITH an explicit human `to` is still a CONTRADICTION and is refused 400
 * `CHANNEL_CHAT_ADDRESSED` (`server/errors.ts`) rather than silently resolved.
 * Addressing a PERSON starts that person's agent on a subject they never saw a
 * title for; asking for someone else's machine is what `request` is for, and it
 * carries the title their consent prompt renders.
 */
const MessageIntentSchema: z.ZodType<MessageIntent> = z.enum([
  "chat",
  "request",
]);

/**
 * How many agents ONE post may address. A multi-address is "@quartz @onyx work
 * together" — a small working set, each of which wakes a real machine — not a
 * mailing list, and every entry costs a resolution + a membership read. Eight
 * is well above any room we have seen and low enough that a runaway loop cannot
 * fan out through it.
 *
 * EXPORTED because the composer has to cap the SAME way: it resolves `@handle`
 * tokens out of the typed body and sends them as `toAgents`, so a body naming
 * nine agents must stop at eight on the client rather than being built into a
 * payload the server rejects wholesale (`lib/mention.ts`). One number, not a
 * restated one.
 *
 * IT BOUNDS THE MERGED ADDRESS, not one field of it. `toAgent` is exactly a
 * one-element `toAgents` and the two are merged before anything is resolved
 * (`server/service-writes-agents.ts`), so the bound that actually holds is
 * enforced there, on the deduped merge. The `.max()` on the array below is the
 * cheap first line for the commonest shape; without the merged check a caller
 * could address NINE — one over every bound the rest of the system states,
 * including `MAX_DERIVED_AGENTS` in `server/service-thread-handshake.ts`, which
 * imports this same constant and would silently truncate the ninth agent out of
 * the handshake thread it was told to join.
 */
export const MAX_ADDRESSED_AGENTS = 8;

/**
 * Post a message or activity event. `body` carries the human-readable
 * render (so the thread needs no special-casing per kind); structured
 * payload rides in `metadata`. `clientMsgId` is the idempotency key.
 *
 * Addressing (v1.1): `toUserId` targets a specific channel member (the
 * service validates it is an active member, else 400) and `summary` is a
 * one-line intent used in the receiver's notification. Both are persisted
 * into `metadata` as `{to_user_id, summary}`.
 *
 * AGENT ADDRESSING (multiplayer): `toAgent` names the agent a message is FOR —
 * an agent id or its handle (`@quartz` minus the `@`), resolved case-folded
 * against THIS channel's agents. `toAgents` is the SAME thing for N agents
 * ("@quartz @onyx work together"); `toAgent` is exactly a one-element
 * `toAgents`. `authorAgentId` names the agent a message is FROM, and is
 * honoured only for that agent's own owner (an agent identity is not
 * assumable). All are stamped as reserved metadata by the server; none is
 * settable through `metadata` (`server/service-writes-metadata.ts`).
 * `toAgent` / `toAgents` are deliberately NOT `.uuid()` — a handle is the point.
 *
 * `toAgents` is `.min(1)`: an EMPTY array is a 400, not a synonym for absence.
 * "Empty means absent" used to be encoded twice — the schema tolerated `[]` and
 * the service quietly folded it into "addressed nobody" — so one behaviour had
 * two homes and neither stated it. Nothing on the wire sends `[]` (the composer
 * spreads the field only when the body resolved mentions; the MCP lane emits it
 * only for a genuine multi-address), so the rule lives once, here, and a caller
 * that builds an empty list is told it addressed nobody instead of learning it
 * from an agent that never woke. The `.max()` is the CHEAP HALF of the bound —
 * see {@link MAX_ADDRESSED_AGENTS} for the merged one that actually holds.
 *
 * `intent` says whether this post is meant to REACH AN AGENT at all — see
 * {@link MessageIntentSchema}.
 */
export const ChannelMessageCreateSchema = z.object({
  body: z.string().min(1).max(16000),
  kind: PostableMessageKindSchema.optional(),
  authorKind: PostableAuthorKindSchema.optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  clientMsgId: z.string().min(1).max(200).optional(),
  toUserId: z.string().uuid().optional(),
  summary: z.string().trim().min(1).max(200).optional(),
  toAgent: z.string().trim().min(1).max(64).optional(),
  toAgents: z
    .array(z.string().trim().min(1).max(64))
    .min(1)
    .max(MAX_ADDRESSED_AGENTS)
    .optional(),
  authorAgentId: z.string().uuid().optional(),
  intent: MessageIntentSchema.optional(),
});
export type ChannelMessageCreateInput = z.infer<
  typeof ChannelMessageCreateSchema
>;

// ─── Tasks (first-class channel tasks, v15) ─────────────────────────────────

/** Task execution mode. `set_task_mode` governs the creator's own machine. */
const TaskModeSchema = z.enum(["interactive", "autonomous"]);

/** How a closed task ended. */
const TaskOutcomeSchema = z.enum(["completed", "failed"]);

/**
 * Create a task in a channel. `title` is the queryable header; `body` is the
 * requester's initial request (posted as the task's first message, addressed
 * to `toUserId`); `mode` defaults to interactive. `toUserId` must be an active
 * member of the channel (validated in the service). `clientMsgId` is an
 * optional idempotency key — a re-sent create_task with the same key returns
 * the already-created task instead of double-creating it (and double-spawning
 * the responder's window), mirroring the message post's idempotency.
 */
export const TaskCreateSchema = z.object({
  title: z.string().trim().min(1).max(200),
  mode: TaskModeSchema.optional(),
  body: z.string().min(1).max(16000),
  toUserId: z.string().uuid(),
  clientMsgId: z.string().min(1).max(200).optional(),
  /**
   * The extra identities admitted to the thread — teammates and/or their agents
   * — which is what turns it into a BREAKOUT ROOM. The creator and `toUserId`
   * are added by the service, so this carries only the EXTRAS. Absent (or
   * empty) means no participant rows at all, which leaves the thread on today's
   * creator/target pair gate.
   */
  participants: ThreadParticipantSeedSchema.optional(),
});
export type TaskCreateInput = z.infer<typeof TaskCreateSchema>;

/**
 * Update a task: close it (`op:"close"` — creator or target, and HUMAN LANE
 * ONLY since 2026-08-04), PROPOSE closing it (`op:"propose_close"` — creator or
 * target, the agent's terminal act), change its mode (`op:"set_mode"` — creator
 * only), OR reopen a closed one (`op:"reopen"` — creator or target, web-only;
 * no MCP counterpart). A discriminated union so the ops can't bleed fields into
 * each other. `reopen` carries no payload — it clears the closed state back to
 * open server-side.
 *
 * `propose_close` deliberately mirrors `close`'s payload (an outcome plus an
 * optional one-line summary) rather than inventing a shape of its own: a
 * proposal is exactly the close it is asking a human to confirm, and the surface
 * that confirms it hands those same two values straight to `close`.
 */
export const TaskUpdateSchema = z.discriminatedUnion("op", [
  z.object({
    op: z.literal("close"),
    outcome: TaskOutcomeSchema,
    summary: z.string().trim().max(2000).optional(),
  }),
  z.object({
    op: z.literal("propose_close"),
    outcome: TaskOutcomeSchema,
    summary: z.string().trim().max(2000).optional(),
  }),
  z.object({ op: z.literal("set_mode"), mode: TaskModeSchema }),
  z.object({ op: z.literal("reopen") }),
]);
export type TaskUpdateInput = z.infer<typeof TaskUpdateSchema>;

/** Per-member notification scope for a channel (self-service preference). */
const NotifyScopeSchema = z.enum(["all", "addressed", "none"]);

/** Per-member responding-agent tool scope (self-service preference). */
const AgentToolProfileSchema = z.enum(["full", "dopl_only", "read_only"]);

/**
 * PATCH /members body: a member updating their OWN per-channel preferences —
 * notify scope and/or agent tool profile. At least one field is required (an
 * empty patch is a no-op the route rejects). Both are self-only: the service
 * always targets the caller's row.
 */
export const ChannelMemberSelfUpdateSchema = z
  .object({
    notifyScope: NotifyScopeSchema.optional(),
    agentToolProfile: AgentToolProfileSchema.optional(),
  })
  .refine((patch) => Object.keys(patch).length > 0, { message: "Empty patch" });
export type ChannelMemberSelfUpdateInput = z.infer<
  typeof ChannelMemberSelfUpdateSchema
>;

export const ChannelMemberAddSchema = z.object({
  userId: z.string().uuid(),
});
export type ChannelMemberAddInput = z.infer<typeof ChannelMemberAddSchema>;

export const ChannelMemberRemoveSchema = z.object({
  userId: z.string().uuid(),
});
export type ChannelMemberRemoveInput = z.infer<
  typeof ChannelMemberRemoveSchema
>;

/**
 * `?since=<seq>&limit=<n<=200>&thread=<taskId>` for a message read.
 *
 * `thread` is a FILTER, not a lookup: it keeps only the rows whose
 * `metadata.taskId` equals it. Deliberately ANY non-empty string — a thread id
 * is a `channel_tasks` uuid today, but the transcript still carries LEGACY
 * `task-<channelId>-<seq>` ids from before threads were a table, and those are
 * real `metadata.taskId` values a reader must be able to isolate. A `.uuid()`
 * here would 400 exactly the exchanges that are hardest to reconstruct by hand.
 *
 * Nothing is checked against `channel_tasks`: an id that matches no row is not
 * an error, it returns `[]`. Length is bounded like `clientMsgId` (the other
 * caller-supplied opaque key) so a filter value can't be unbounded.
 */
export const MessageReadQuerySchema = z.object({
  since: z.coerce.number().int().nonnegative().optional(),
  limit: z.coerce
    .number()
    .int()
    .positive()
    .max(MAX_MESSAGE_LIMIT)
    .optional()
    .default(DEFAULT_MESSAGE_LIMIT),
  thread: z.string().trim().min(1).max(200).optional(),
});
export type MessageReadQuery = z.infer<typeof MessageReadQuerySchema>;

/**
 * `?since=<seq>&timeoutMs<=50000&excludeAuthor=<userId>` for the await
 * long-poll. `excludeAuthor` is OPT-IN: the desktop listener omits it because
 * it needs its own account's messages (thread targeting, requester-window
 * routing, version-skew observation), while an MCP await passes the caller's
 * own id so the caller's own posts cannot pop its own hold.
 */
export const AwaitQuerySchema = z.object({
  since: z.coerce.number().int().nonnegative().optional(),
  timeoutMs: z.coerce
    .number()
    .int()
    .positive()
    .max(MAX_AWAIT_TIMEOUT_MS)
    .optional(),
  excludeAuthor: z.string().uuid().optional(),
});
export type AwaitQuery = z.infer<typeof AwaitQuerySchema>;

// ─── Consent (inbound consent + outbound review) ────────────────────────────

/**
 * The triggering message's `seq`. NOT coerced: this arrives in a JSON body,
 * where `z.coerce.number()` would silently turn `null` / `""` / `[]` into 0
 * and `true` into 1 — a de-dupe key must never be manufactured out of junk.
 * (Coercion belongs on query strings, where everything is a string by
 * definition.) `seq` is a 1-based identity column, so 0 is not a real seq.
 */
const ConsentMessageSeqSchema = z.number().int().positive();

/** Fields every consent create carries, whatever the kind. */
const consentCreateBase = {
  channelId: z.string().uuid(),
  summary: z.string().trim().max(200).optional().default(""),
  bodyPreview: z.string().max(16000).optional().default(""),
};

/**
 * Create a consent request. The desktop POSTs this when a trigger fires
 * (inbound) or a reply is drafted (outbound). `operatorUserId` is NEVER in the
 * body — it is always the authenticated caller (a caller can only raise a
 * request addressed to themselves). `requesterUserId` is derived server-side
 * from the triggering message. `summary` shares the message summary's cap
 * (it renders on the card); `bodyPreview` / `proposedReply` are larger.
 *
 * A discriminated union on `kind` so the two shapes can't bleed into each
 * other: only an OUTBOUND request carries a `proposedReply` (an inbound row
 * with a drafted reply is nonsense, and accepting one let a caller pre-seed
 * the outbound review's payload). `messageSeq` is meaningful for BOTH kinds —
 * it is the de-dupe key (inbound: the triggering message; outbound: the
 * message the reply answers), so a retry can't stack duplicate cards.
 */
export const ConsentCreateSchema = z.discriminatedUnion("kind", [
  z.object({
    ...consentCreateBase,
    kind: z.literal("inbound"),
    messageSeq: ConsentMessageSeqSchema.optional(),
  }),
  z.object({
    ...consentCreateBase,
    kind: z.literal("outbound"),
    messageSeq: ConsentMessageSeqSchema.optional(),
    proposedReply: z.string().max(16000).optional(),
  }),
]);
export type ConsentCreateInput = z.infer<typeof ConsentCreateSchema>;

/**
 * Which human surface recorded the decision — persisted verbatim into
 * `decided_by` for the audit trail. The desktop's native dialog sends
 * `decidedBy: 'desktop'`; the web UI omits it and defaults to `web`.
 * `trust` is server-generated only (a standing rule, not a human click) and
 * is deliberately NOT accepted from a caller.
 */
const ConsentDecidedBySchema = z.enum(["web", "desktop"]);

/** PATCH /consent/[id] body: the operator's decision + which surface made it. */
export const ConsentDecisionSchema = z.object({
  decision: z.enum(["allow", "deny"]),
  decidedBy: ConsentDecidedBySchema.optional().default("web"),
});
export type ConsentDecisionInput = z.infer<typeof ConsentDecisionSchema>;

/**
 * Consent inbox filter. `pending` (the default, and what the web inbox
 * renders) keeps the card list to things that still need an answer;
 * `decided` is the audit view — it is the ONLY way to read the
 * `auto_allowed` rows a trust rule writes, i.e. "your agent ran N times
 * without asking"; `all` is both.
 */
const ConsentStatusFilterSchema = z.enum(["pending", "decided", "all"]);
export type ConsentStatusFilter = z.infer<typeof ConsentStatusFilterSchema>;

/** `?channelId=<uuid>&status=<pending|decided|all>` for the consent inbox. */
export const ConsentListQuerySchema = z.object({
  channelId: z.string().uuid().optional(),
  status: ConsentStatusFilterSchema.optional().default("pending"),
});
export type ConsentListQuery = z.infer<typeof ConsentListQuerySchema>;

// ─── Trust (per-teammate standing consent) ──────────────────────────────────

/** POST / DELETE /trust body: the teammate whose agent is (un)trusted. */
export const TrustMutateSchema = z.object({
  trustedUserId: z.string().uuid(),
});
export type TrustMutateInput = z.infer<typeof TrustMutateSchema>;

// ─── Presence (desktop heartbeat) ───────────────────────────────────────────

/**
 * POST /presence body: an optional status label (defaults to 'listening').
 * A closed enum, not free text — the column is rendered as a listener state
 * and a matching CHECK constraint backs it in the database, so an arbitrary
 * string can't be written through the heartbeat and then surfaced in the UI.
 */
export const PresenceHeartbeatSchema = z.object({
  status: z.enum(["listening", "busy", "paused", "offline"]).optional(),
});
export type PresenceHeartbeatInput = z.infer<typeof PresenceHeartbeatSchema>;
